### ISSUE TITLE
UTF-8 characters

### ISSUE THREAD

**Issue by p53** [ecoshub/stable#10]
when using heavy checkmark column width is not properly calculated, this might be issue https://henvic.dev/posts/go-utf8/

**Comment by ecoshub** [comment]
Hi! Thanks for taking time to create this issue. Can you provide an example input and output please?

**Comment by p53** [comment]
input 

```
type Val struct {
  CheckMark string
}

type Vals struct {
  Values []*Val
}

vals := &Vals{}
val := &Val{CheckMark: "\u2714"}
arr := make([]*Val, 0)
arr = append(arr, val)
vals.Values = arr
```

output:
```
|  CheckMark |
|  heavy-checkmark-symbol                    |
```

**Comment by ecoshub** [comment]
Hi there again.
I am not able to reproduce this issue

main.go
```go
package main

import (
	"fmt"

	"github.com/ecoshub/stable"
)

func main() {
	type Val struct {
		CheckMark string
	}

	type Vals struct {
		Values []*Val
	}

	vals := &Vals{}
	val := &Val{CheckMark: "\u2714"}
	arr := make([]*Val, 0)
	arr = append(arr, val)
	vals.Values = arr

	fmt.Println("first print")
	// first print
	stable.Print(vals)

	fmt.Println("second print")
	// second print
	stable.Print(vals.Values)

	t, err := stable.ToTable(vals.Values)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println("third print")
	// third print
	fmt.Println(t)
}

```

output:
```
first print
+------------------+
|       Vals       |
|------------------|
|      Values      |
|------------------|
|  [0xc0000103d0]  |
+------------------+

second print
+-------------+
|  CheckMark  |
|-------------|
|  ✔          |
+-------------+

third print
+-------------+
|  CheckMark  |
|-------------|
|  ✔          |
+-------------+
```

go.mod
```
module test/stable

go 1.16

require github.com/ecoshub/stable v1.0.3
```

Am I missing something....

**Comment by p53** [comment]
yes that is the issue, do you see that check mark column is not aligned..., that is what i am reporting..., probably length of character not properly calculated

**Comment by ecoshub** [comment]
Ooo now I get it :))  Yes there is one more space char at the end. Thank you

**Comment by ecoshub** [comment]
I think there is another issue on this problem. Because I am only seeing this "extra space" from my mobile phone but when I am on my laptop there is no "extra space". Everything seems OK. 😄

## This is the screen shot from my laptop (macOS chrome Version 103.0.5060.134 (Official Build) (x86_64)):
<img width="809" alt="Screen Shot 2022-08-14 at 22 09 25" src="https://user-images.githubusercontent.com/43964183/184551465-72551fd0-ec46-46c2-ae35-8c5f4a7282fc.png">
 
## And this is screenshot from my mobile phone:
![WhatsApp Image 2022-08-14 at 22 06 28](https://user-images.githubusercontent.com/43964183/184551538-8a484c64-443b-429d-a317-456476fe7237.jpeg)

Did you notice that?

**Comment by p53** [comment]
@ecoshub sorry, why did you closed it? I see this issue when working in terminal...i see that there is possible issue also related to browsers but for sure you will see this issue in terminal, did you tried it in linux/mac terminal??

**Comment by ecoshub** [comment]
@p53  tested with:
```
zsh    alacritty (Linux ecomain 5.17.4-arch1-1 x86_64 GNU/Linux)
sh     alacritty (Linux ecomain 5.17.4-arch1-1 x86_64 GNU/Linux)
zsh    xfce      (Linux ecomain 5.17.4-arch1-1 x86_64 GNU/Linux)
sh     xfce      (Linux ecomain 5.17.4-arch1-1 x86_64 GNU/Linux)
zsh    alacritty (Darwin  21.3.0 Darwin Kernel Version 21.3.0 x86_64)
bash   alacritty (Darwin  21.3.0 Darwin Kernel Version 21.3.0 x86_64)
sh     alacritty (Darwin  21.3.0 Darwin Kernel Version 21.3.0 x86_64)
zsh    warp      (Darwin  21.3.0 Darwin Kernel Version 21.3.0 x86_64)
bash   warp      (Darwin  21.3.0 Darwin Kernel Version 21.3.0 x86_64)
sh     warp      (Darwin  21.3.0 Darwin Kernel Version 21.3.0 x86_64)
```
no extra space.

think about it if I update "column width" function those setups gonna fail this time.
if you have any solution please share with me I would be happy to see a solution.
